### Obtener todas las películas
# Llama al endpoint GET /movie
# Devuelve un arreglo con todas las películas almacenadas
GET http://localhost:3000/movie

### Obtener película por ID
# Llama al endpoint GET /movie/:id
# En este caso, busca la película con id = 1
GET http://localhost:3000/movie/1

### Crear una película
# Llama al endpoint POST /movie
# Crea una nueva película con los datos enviados en formato JSON
POST http://localhost:3000/movie
Content-Type: application/json
{
    "id": 1,
    "titulo": "Inception",
    "año": 2010,
    "genero": "Ciencia ficción"
}

### Crear otra película
# Igual que el anterior, pero con otro id y título distinto
POST http://localhost:3000/movie
Content-Type: application/json
{
    "id": 2,
    "titulo": "Interstellar #1",
    "año": 2014,
    "genero": "Ciencia ficción"
}

### Eliminar película por ID
# Llama al endpoint DELETE /movie/:id
# En este caso, elimina la película con id = 1
DELETE http://localhost:3000/movie/1

### Eliminar otra película
# Elimina la película con id = 2
DELETE http://localhost:3000/movie/2
