### Obtener todos los directores
# Llama al endpoint GET /director
# Devuelve un arreglo con todos los directores almacenados en memoria
GET http://localhost:3000/director

### Obtener director por ID
# Llama al endpoint GET /director/:id
# En este caso, busca al director con id = 1
GET http://localhost:3000/director/1

### Crear un director
# Llama al endpoint POST /director
# Crea un nuevo director con los datos enviados en formato JSON
POST http://localhost:3000/director
Content-Type: application/json
{
    "id": 1,
    "nombre": "Quentin Tarantino",
    "fechaNacimiento": "1963-03-23",
    "nacionalidad": "Latinoamericano"
}

### Crear otro director
# Similar al anterior, pero con un id distinto
POST http://localhost:3000/director
Content-Type: application/json
{
    "id": 2,
    "nombre": "Steven Spielberg",
    "fechaNacimiento": "1949-06-22",
    "nacionalidad": "Mexicano"
}

### Eliminar director por ID
# Llama al endpoint DELETE /director/:id
# En este caso, elimina al director con id = 1
DELETE http://localhost:3000/director/1
